twig:
    default_path: '%kernel.project_dir%/templates'

    globals:
        year: 2023
        messe_count: 23
        ega_count: 28
        endDate: 'March 15, 2023 23:59'

    form_themes: ['bootstrap_5_layout.html.twig']

when@test:
    twig:
        strict_variables: true
