twig:
    default_path: '%kernel.project_dir%/templates'

    paths:
      '%kernel.project_dir%/public/css': css
      '%kernel.project_dir%/public/images': images

    globals:
        year: 2023
        messe_count: 24
        ega_count: 29
        deadline: 'Apr 30, 2023 23:59'
        endDate: 'May 11, 2023 23:59'
        limit_service: '@App\Service\LimitService'

    form_themes: ['bootstrap_5_layout.html.twig']

when@test:
    twig:
        strict_variables: true
