twig:
    default_path: '%kernel.project_dir%/templates'

    paths:
      '%kernel.project_dir%/public/css': css
      '%kernel.project_dir%/public/images': images

    globals:
        year: 2024
        messe_count: 25
        ega_count: 30
        deadline: 'Apr 21, 2024 23:59'
        endDate: 'May 1, 2024 23:59'
        limit_service: '@App\Service\LimitService'
        limit_messe: '%app.limit.messe%'
        limit_ega: '%app.limit.ega%'

    form_themes: ['bootstrap_5_layout.html.twig']

when@test:
    twig:
        strict_variables: true
